### ISSUE TITLE
#Carga de plana: El icono de descarga no hace nada, no muestra un mensaje ni nada, NO TIENE FUNCIONALIDAD 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#1004]
![image](https://user-images.githubusercontent.com/20443614/27688056-cc5b936a-5c9e-11e7-906c-aa4c6d229e29.png)

**Comment by emartinezd** [comment]
ESTO NO ES CARGA DE PLANA, ES CARGA DE CARRO
