### ISSUE TITLE
#Revisión Embarque: Solo puedo eliminar el paquete antes de guardarlo 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#1053]
Tengo un paquete (rojo) que no se encuentra en ningún embarque
Paquete (azul) que ya fue guardado en el embarque
![image](https://user-images.githubusercontent.com/20443614/27846267-77df7e58-60fb-11e7-84f7-99fd77103149.png)

El que no se encuentra guardado si lo puedo eliminar de la captura 
![image](https://user-images.githubusercontent.com/20443614/27846308-c5d8dc58-60fb-11e7-86ab-8334ad6ca396.png)

pero el otro no 
![image](https://user-images.githubusercontent.com/20443614/27846312-d3ecdb28-60fb-11e7-9e11-2a3ebd97b5d9.png)

**Comment by jgutierrez01** [comment]
Esto quedó asi ya que pidieron de que todos los spools o paquetes que se agreguen de forma manual si se podran eliminar de la captura, pero si ya venian incluidos en la revision no dejaba eliminarlos, ya que se les quitó el icono de eliminar a los paquetes que ya venían incluidos en la revision.
