### ISSUE TITLE
#Listado de embarques cerrados: No coincide las fechas seleccionadas en la linea de captura con el grid 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#1069]
![image](https://user-images.githubusercontent.com/20443614/28044101-0463d43e-659b-11e7-817e-f50ac35632aa.png)

**Comment by jgutierrez01** [comment]
Es Incorrecto eso, se toma en cuenta la fecha de envío, no la fecha de permiso
