### ISSUE TITLE
#Encintado 6EN: No se muestra el catalogo 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#107]
selecciono el tipo de busqueda por spool id contiene  y no se muestra el catalogo de el spool **p217**
![image](https://cloud.githubusercontent.com/assets/20443614/21243193/6b44fca2-c2dd-11e6-852c-28e595b2b5f5.png)
![image](https://cloud.githubusercontent.com/assets/20443614/21244544/c26c95de-c2e3-11e6-852c-9bc5db262cbb.png)

pero si selecciono el filtro de busqueda por zona y filtro por el mismo spool se muestra el catalogo de dicho spool 
![image](https://cloud.githubusercontent.com/assets/20443614/21244295/9343d0ac-c2e2-11e6-900a-5dad97467047.png)

> `_Esto paso con varios spools_`

 
![image](https://cloud.githubusercontent.com/assets/20443614/21244686/63a13d74-c2e4-11e6-9528-a6a4ce570ea3.png)

**Comment by iriscsd** [comment]
Mery para este caso esta bien que los catologos no obtengan información ya que para el Proyecto "PESQUERIA CTP - TECHINT" no existen niguna relacion con el usuario en sesion "Sam Admin". El issue es que no debe cargar informacion en el grid con ese proyecto o mejor dicho con el SpoolID contiene. 

Se corrige issue!
