### ISSUE TITLE
#WPS 5W:

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#112]
Los campos marcados en azul bajarles un poco el color como los campos en rojo 
![image](https://cloud.githubusercontent.com/assets/20443614/21245545/a15e1a8e-c2e8-11e6-9e34-a6620af88ffd.png)

**Comment by emartinezd** [comment]
los checkbox, asi estan en todos, lo demas ya se estan del mismo tono
