### ISSUE TITLE
#WPS 7W: El sistema me permire cambiar el pqr a pesar de que no coincide  los grupos P

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#114]
Cambio el PQR  **PQR-24102016** por ER-10, el sistema me manda un warning de que no coincide los grupos p sin embargo se cambia la informaciòn 
![image](https://cloud.githubusercontent.com/assets/20443614/21245814/5c9031ec-c2ea-11e6-8135-c960e8cd8273.png)

Doy clic en guardar (No me sale el warning de tipo correcto ), pero se cambia el btn de acciones a Editar
![image](https://cloud.githubusercontent.com/assets/20443614/21245851/9f35423a-c2ea-11e6-8aa3-48faefd50555.png)

**Comment by emartinezd** [comment]
Asi lo pidio yair, se valida al momento de dar guardar
