### ISSUE TITLE
#Carga de Plana 3CP: No se  filtra los M2

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#133]
Para los spools X001- 001 y x001-002 tengo M2 que inician con 3 
![image](https://cloud.githubusercontent.com/assets/20443614/21373983/ac61bbc6-c6e8-11e6-94bd-7524c82bffb9.png)
Filtre M2 por el numero 3 pero no se muestra nada.
![image](https://cloud.githubusercontent.com/assets/20443614/21374002/e82cc2a4-c6e8-11e6-807f-107170d4a885.png)

**Comment by iriscsd** [comment]
Este issues es de la pantalla **Empaquetado**

**Comment by iriscsd** [comment]
No es un issue ya que de acuerdo con el filtro se tiene que escribir exactamente igual el numero que deseas buscar. 

![imagen](https://cloud.githubusercontent.com/assets/19808736/21410795/02103884-c7a9-11e6-98ed-f8fc8918813c.png)
