### ISSUE TITLE
#Encintado 12EN: centrar el texto de popup 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#190]
![image](https://cloud.githubusercontent.com/assets/20443614/21487259/a64db4aa-cb8a-11e6-87fe-bd5e349d2413.png)

**Comment by MeriverQuerido** [comment]
![image](https://cloud.githubusercontent.com/assets/20443614/21487258/9717604e-cb8a-11e6-8d30-c04a6e9768e8.png)

**Comment by iriscsd** [comment]
El PopUp en QA aparece de esta manera
![imagen](https://cloud.githubusercontent.com/assets/19808736/21505718/88ed98da-cc2f-11e6-8b98-d0ef71a68993.png)
