### ISSUE TITLE
#Preparaciòn Embarque 7EM: El combo de plana no se autoselecciona la unica opcion del catalogo 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#194]
Si solo se muestra una opcion en el catalogo se debe mostrar por default 
![image](https://cloud.githubusercontent.com/assets/20443614/21507908/1adc8906-cc42-11e6-809a-322f70feba1e.png)

**Comment by iriscsd** [comment]
Mery para este combo no se debe autoseleccionar ya que se encuentra en la seccion agregar, el usuario debe selccionar que planas debe seleccionar

**Comment by iriscsd** [comment]
Mery para este combo no se debe autoseleccionar ya que se encuentra en la seccion agregar, el usuario debe selccionar que planas debe agregar al embarque
