### ISSUE TITLE
#Empaquetado 001EM: El sistema no me muestra planas en el catalogo 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#197]
quiero cargar un paquete cerrado a una plana que pertenezca al proyecto etleno XXI, pero al seleccionar plana no se muestra nada en el catalogo
![image](https://cloud.githubusercontent.com/assets/20443614/21509071/53c485bc-cc4b-11e6-8cc8-3638a9d44509.png)
Sin embargo en la pantalla de carga de plana, se muestran 3 planas en el proyecto etlleno 
![image](https://cloud.githubusercontent.com/assets/20443614/21509086/7173afb6-cc4b-11e6-8811-82fff77724b7.png)

**Comment by iriscsd** [comment]
Mery solo mostrará planas que esten abiertas en la pantalla **Empaquetado**, 
![imagen](https://cloud.githubusercontent.com/assets/19808736/21533245/32befee6-cd1e-11e6-9fce-ba78a1bfc152.png)
