### ISSUE TITLE
#PQR/ WPS : El sistema no permite modificar un PQR que ya fue eliminado de un WPS

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#210]
Quiero modifiar un PQR pero al dar clic sobre el nombre, el sistema manda un mensaje que ya esta asignado en en wps 
![image](https://cloud.githubusercontent.com/assets/20443614/21532354/f69defca-cd14-11e6-9cf1-99457bef47eb.png)

Asi que en la pantalla de WPS consulto para saber si el PQR esta asigando a un WPS, pero no lo esta 
![image](https://cloud.githubusercontent.com/assets/20443614/21532427/b1c131c2-cd15-11e6-93dd-2dd7286b8b11.png)

**Comment by emartinezd** [comment]
este ya esta resuelto, solo falta publicar
