### ISSUE TITLE
#22 Entrega de placas o graficas

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#22]
¿Por qué al iniciar la captura se muestra en la columna C. Físicas sin luz (Aprobado ), pero aun no capturo nada?
Es una regla que así se inicie la captura 
.
![image](https://cloud.githubusercontent.com/assets/20443614/20608626/21d9c2ea-b249-11e6-9a5c-8c0a2d70b6a4.png)

**Comment by iriscsd** [comment]
Mery es una regla de negocio que solicito Yair, ya que si el spool aun no existe en la captura por default es aprobado
