### ISSUE TITLE
#Sistema de pintura: Que no salgan los Ceros 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#298]
Una de las observaciones que mencino Yair, fue que no le gustaba que se mostrara el cero 
![image](https://cloud.githubusercontent.com/assets/20443614/21860662/3b7b38b8-d7f7-11e6-998d-03fa214125a2.png)
Ya que se tiene que borrar el cero para escribir la cantidad, 
Ejemplo, si escribo el 1, como esta el cero se convierte en 10
![image](https://cloud.githubusercontent.com/assets/20443614/21860786/d573c020-d7f7-11e6-8005-3812a6f47b43.png)

**Comment by rrojasl** [comment]
Este issue se tiene que platicar con Sergio porque esto es del framework de kendo si algo es de tipo numérico automáticamente le agrega el 0 pero si lo que quiere es no borrar entonces se tendría que extender la funcionalidad ... es decir cuando se ingrese al control autoseleccionar el contenido y si el usuario ingresa algo entonces automáticamente se borraría. pero esto se debería implementar en todas las pantallas y así no lo ah pedido.

**Comment by MeriverQuerido** [comment]
Queda pendiente hablar con Sergio - El issue tiene estatus invalid   @rrojasl
