### ISSUE TITLE
#Soldadura: No se ejecuta la validaciòn, con lo que se realiza

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#345]
¿Cuales son los campos mandatorios para guardar un soldador?
-El sistema me permite guardar la fila sin iformacion, agregar un popup que diga los campos mandatorios 
![image](https://cloud.githubusercontent.com/assets/20443614/22069845/7b6198e2-dd5f-11e6-8e84-7296095f443b.png)

En el segundo caso, ya tengo el soldador, asi que el pop up debe de decir que la colada es campo mandatorio.
![image](https://cloud.githubusercontent.com/assets/20443614/22070146/919187de-dd60-11e6-80a8-de84a12a8eca.png)

**Comment by emartinezd** [comment]
quieres que mande un mensaje por cada caso? asi no son las validaciones de los grids


revisare solo el bug de la fila totalmente vacia
