### ISSUE TITLE
#Soldadura: Hay un load antes de abrir el popup.

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#347]
Al dar clic en el hipervinculo, sale un load y despues se abre el popup.
![image](https://cloud.githubusercontent.com/assets/20443614/22070407/852fa592-dd61-11e6-80f9-4874263410a3.png)

**Comment by emartinezd** [comment]
Es correcto por que todo se obtiene por medio de ajax, dinamicamente
