### ISSUE TITLE
#Soldauda: Falta un pop cuando se cambie el  tipo de captura de spool a Jta y viceversa 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#351]
Si  estoy capturando por spool y slecciono el btn de Jta  
![image](https://cloud.githubusercontent.com/assets/20443614/22071571/284b8d24-dd65-11e6-943b-3f4ec8ef01d9.png)
El sistema debe de mostrar el siguiente mensaje 
![image](https://cloud.githubusercontent.com/assets/20443614/22071609/4c059570-dd65-11e6-8bf9-1cae1cd81056.png)

**Comment by emartinezd** [comment]
TIenes 2 lineas de esto
