### ISSUE TITLE
#Soldadura: Cada que cambio la informmaciòn de la columna de proceso de raiz o relleno se elimina mi WPS

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#355]
¿Es correcto que se elimine mi Wps?
![image](https://cloud.githubusercontent.com/assets/20443614/22073869/1f480c96-dd6c-11e6-8c15-28e8255cb030.png)

**Comment by emartinezd** [comment]
Por que hace ajax,  consulta en BD que WPS estan certificados para ambos procesos, si lo cambias, hace el llamado y limpia, pero igual, no se menciono, habra que confirmar con yair el funcionamiento
