### ISSUE TITLE
#Soldadura: El titulo del popup de soldadores de Relleno no es el correcto 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#359]
El titulo es Soldadores de Relleno 
![image](https://cloud.githubusercontent.com/assets/20443614/22075938/a1345686-dd73-11e6-9b75-3c363c54eae6.png)

Al igual centrar las X

**Comment by emartinezd** [comment]
Ya lo hice yo, no asignes nada de soldadura a edgar, aunque sea estetico ahorita, por favor
