### ISSUE TITLE
#Etiquetado: No se muestran spools cuando selecciono el tipo de busqueda por spool ID

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#364]
![image](https://cloud.githubusercontent.com/assets/20443614/22115650/77fb812a-de33-11e6-8772-9c723008b8ef.png)

Pero en encintado si hay spools 
![image](https://cloud.githubusercontent.com/assets/20443614/22115667/880d4486-de33-11e6-9614-edf881e5d1c6.png)

**Comment by MeriverQuerido** [comment]
@iriscsd  sigo teniendo problea con este issue

**Comment by iriscsd** [comment]
PUEDES CHECARLO DE NUEVO PORFA
