### ISSUE TITLE
#Listado Embarque: pruebas en ingles 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#374]
![image](https://cloud.githubusercontent.com/assets/20443614/22129468/d06449ae-de6b-11e6-938a-37d4b31141e5.png)

Este popup sale cuando se llena la fila con informaciòn, y se da clic en enviar

**Comment by MeriverQuerido** [comment]
@edgarsantacruz19  el input de Client shipment num, esta mas abajo de los demàs, podrias ponerlo a la misma altura de los demàs sin afectar el diseño cuando este en español.

**Comment by iriscsd** [comment]
Ya corregi lo del titulo del PopUp
