### ISSUE TITLE
#Sistema de Pintura:  La informacion del Grid desaparece despues de guardar 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#396]
Capturo la siguiente informaciòn 
![image](https://cloud.githubusercontent.com/assets/20443614/22310288/6a600bcc-e314-11e6-9de8-85303314fcaa.png)

Como se puede visualizar hay un proceso que requiere color para que se pueda guardar la captura, por lo tanto el sistema debe de mostrar un popup que al menos debe seleccionarse un color para el guardado.
Selecciono un color y doy clic en guardar 
Despues la informacion que esta en el grid desaparece
![image](https://cloud.githubusercontent.com/assets/20443614/22310392/b72afae8-e314-11e6-85a4-60fae3890f60.png)
y al dar clic en editar, el campo de proyecto se convierte en combo box, eso me limita a seleccionar solo un proyecto, pero ¿Que pasa si quiero seleccionar mas de 2 proyectos?
![image](https://cloud.githubusercontent.com/assets/20443614/22310432/d84835a6-e314-11e6-8652-7a6a8f509c86.png)

**Comment by rrojasl** [comment]
Se hablo con Sergio y dijo que esta funcionalidad estaba bien.
