### ISSUE TITLE
#Soldadura: Al guardar se muetra un mensaje en rojo 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#404]
Agrego spools al Grid de 2 proyectos difrente capturo toda la informacion, doy clic en el btn de guardar inferior y el sistema muestra un mensaje en rojo.
![image](https://cloud.githubusercontent.com/assets/20443614/22428993/b6181880-e6ce-11e6-842d-5b307d9bea68.png)

**Comment by emartinezd** [comment]
lo podrias volver a probar por favor? 
 es que eso me suena a error del servidor de BD no del Stored si sigue, me pones aqui en mensaje
