### ISSUE TITLE
#Soldadura: Agregar un load despues de guarda 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#410]
Aun no termina de cargar la informaciòn y ya se cambio al btn de Editar 
![image](https://cloud.githubusercontent.com/assets/20443614/22433132/ef7f1f8e-e6dc-11e6-9c4f-3773d1d7dbab.png)

**Comment by emartinezd** [comment]
am... si tiene el load o.O algun caso en particular?

**Comment by MeriverQuerido** [comment]
@emartinezd  la informacion del grid sale por pausas
