### ISSUE TITLE
#Soldadura: De que depende, que se muestre el popup de trabajos adicionales 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#411]
- Solo se muestra el popup de trabajos adicionales cuando hay informaciòn de proceso de relleno y de raiz.

**Comment by emartinezd** [comment]
Era un error, ya esta corregido, depende que haya al menos un soldador ya sea en raiz o en relleno, ya que son esos mismos soldadores
