### ISSUE TITLE
#Armado: Se siguen mostrando los spool a pesar de que se enviaron en una embarque 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#417]
![image](https://cloud.githubusercontent.com/assets/20443614/22443785/c98ca750-e705-11e6-81f2-7495b556aaee.png)

Ya se envio en un embarque dichos spools.
![image](https://cloud.githubusercontent.com/assets/20443614/22443904/5484a59c-e706-11e6-9474-1bd7126d7c20.png)

**Comment by rrojasl** [comment]
No es error del modulo recuerda revisar la tabla Sam3_SpoolWorkStatus la columna spoolcertificado tiene que tener el valor asignado 1.
