### ISSUE TITLE
#Listado de sistema de pintura: Quitar el popup de Eliminar 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#442]
![image](https://cloud.githubusercontent.com/assets/20443614/22562452/3310a990-e942-11e6-8d3d-1b6454405bb7.png)

**Comment by rrojasl** [comment]
como no tiene el boton guardar tiene que mostrarse la ventana.

solo elimine la x de la parte superior derecha.
