### ISSUE TITLE
#Sistema de pintura aplicable: No funciona correctamente el planchado 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#445]
Selecciono para cada spool un sistema de pintura.
En la secciòn de planchado selecciono el sistema de pintura **18.1 Sala** que tiene en el catalogo de colores **Rojo**, sera aplicado a los campos vacios , sin embargo al dar clic en aplicar este no se asigna el color a los sistemas de pintura **18.1 Sala**

![image](https://cloud.githubusercontent.com/assets/20443614/22563992/6290bd4e-e948-11e6-80e6-2af868fbfb41.png)

**Comment by rrojasl** [comment]
Se tiene que definir el planchado el motivo se esta tomando como "vacio" el sistema de pintura-color
por lo tanto en el ejemplo que ingresaste no se puede planchar porque el sistema de pintura "no esta vacio"

**Comment by rrojasl** [comment]
platicamos la funcionalidad con Sergio y si se requiere se cambia.
