### ISSUE TITLE
#Sistema de pintura aplicable: Las filas se marcan en rojo en filas que tienen la captura correcta 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#446]
![image](https://cloud.githubusercontent.com/assets/20443614/22564497/608a7c68-e94a-11e6-93ce-b0d707f4009f.png)

**Comment by rrojasl** [comment]
Esto es porque se necesita ingresar previamente el spool en la tabla de Sam3_SP_SpoolAplicable para después el sistema "Edite" el sistema de pintura.
