### ISSUE TITLE
#Sistema de pintura aplicable: El sistema no me permite guardar 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#449]
Se marcan las filas en rojo al dar clic en guarda, asi que el sistema muestra un popup de toma de decisiòn "Los datos marcados en rojo no se guardaran", por lo tanto debe continuar con la captura, pero no es asi el sistema muestra un mensaje de tipo advertencia "No hay datos por guardar"
![image](https://cloud.githubusercontent.com/assets/20443614/22564814/7c9b3a40-e94b-11e6-9ebf-064395b8e7ae.png)

**Comment by rrojasl** [comment]
Se acordó con yair que primero se tiene que editar una tabla donde el como administrador iba a ingresar los spools con un sistema de pintura por esa razon muestra mensajes en rojo. cambiare el mensaje para una mejor orientación.
