### ISSUE TITLE
#Sistema de pintura apicable: El catalogo de sistema de pintura no coincide con el listado  

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#471]
*Catalogo de sistema de pintura de la pantalla SPAplicable
![image](https://cloud.githubusercontent.com/assets/20443614/22907712/2ad18f84-f210-11e6-8ae9-cc1a97152738.png)

*Catalogo del listado:
![image](https://cloud.githubusercontent.com/assets/20443614/22907756/584fbb3e-f210-11e6-80e2-b0ff05ecaa2e.png)

**Comment by rrojasl** [comment]
truncar las tablas de sistema de pintura ya que se debe a incongruencia por pruebas .
