### ISSUE TITLE
#Captura soldadura: Error en la oración 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#501]
En la **captura** 
![image](https://cloud.githubusercontent.com/assets/20443614/23190888/5245018a-f860-11e6-895e-d98e9202412a.png)

![image](https://cloud.githubusercontent.com/assets/20443614/23190899/6a5d86c0-f860-11e6-9d2b-a876f78000e4.png)

**Comment by emartinezd** [comment]
que debe decir?
@emartinezd  YA EXISTE EN LA CAPTURA
