### ISSUE TITLE
#Captura Soldadura: Los trabajos adicionales no se quitan de manera dinamica

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#522]
Al eliminar un soldador de relleno 
![image](https://cloud.githubusercontent.com/assets/20443614/23215908/a4f2963a-f8d9-11e6-8c2e-37bf6d71c0da.png)

![image](https://cloud.githubusercontent.com/assets/20443614/23215935/c0194184-f8d9-11e6-9b48-745fc46b92ca.png)

Pero en el detalle, hay un trabajo adicional 
![image](https://cloud.githubusercontent.com/assets/20443614/23215959/d5aa748c-f8d9-11e6-9271-d0f13a8b79c5.png)

Al abrir el popup no hay trabajos adicionales, confunde al usuario con que no elimino los trabajos adicionales 
![image](https://cloud.githubusercontent.com/assets/20443614/23215980/ea26f872-f8d9-11e6-81c2-9100102a1cd6.png)

**Comment by emartinezd** [comment]
No se cambia el template, por que los trabajos si se cambian
