### ISSUE TITLE
#Empaquetado: Desaparece el paquete de el input de  paquete despues de guardar 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#526]
En el popup para guardar un paquete que contiene 2 spools del proyecto etileno 
![image](https://cloud.githubusercontent.com/assets/20443614/23220479/c861fe7c-f8e7-11e6-9343-5d7016cd11f0.png)

Despues de dar clic en guardar, en el input de paquete ya no se muestra el nombre del paquete 
![image](https://cloud.githubusercontent.com/assets/20443614/23220602/21210ce2-f8e8-11e6-81a1-c893c672788d.png)

![image](https://cloud.githubusercontent.com/assets/20443614/23220621/2dca3c7a-f8e8-11e6-9753-9410d99d917a.png)

**Comment by iriscsd** [comment]
Tienes el flujo? ya lo replique y todo sale bien
