### ISSUE TITLE
#Armado: Se marcan las filas en rojo que ya estan capturadas correctamente.

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#531]
Agrego spools al grid, como se muestra en la siguiente imagen.
![image](https://cloud.githubusercontent.com/assets/20443614/23237602/bf94eb24-f923-11e6-8b74-8298ff8c34cd.png)

dejo en blanco el unico 2 y al guardar se marca en rojo 
![image](https://cloud.githubusercontent.com/assets/20443614/23237711/2a5754b0-f924-11e6-8bd5-fe4ecd942386.png)

Vuelvo a ingresar el unico2, y dejo vacio el unico2 del spool que se encuentra encerrado en azul, al dar clic en guardar ambas filas se marcan en rojo, pero una esta capturada correctamente.
![image](https://cloud.githubusercontent.com/assets/20443614/23237776/7b59652e-f924-11e6-8b0d-7afc3318a8c2.png)

**Comment by rrojasl** [comment]
Hay dependencia entre numeros unicos entonces ambos registros tienen que estar completos asi lo comento yair.
