### ISSUE TITLE
#Captura Soldadura: EL WPS que esta seleccionado para un spool no se encuentra en el listado

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#536]
El WPS es WPS-012
![image](https://cloud.githubusercontent.com/assets/20443614/23270635/1c62c4e8-f9ba-11e6-94fb-bee7de772436.png)

Sin embargo al consultar el listado no se encuentra el WPS
![image](https://cloud.githubusercontent.com/assets/20443614/23270667/33b6ab1e-f9ba-11e6-8bf2-cf0c0cf2ed8a.png)

**Comment by emartinezd** [comment]
por que cambiaron la configuracion, y lo subi mal, borra todo
