### ISSUE TITLE
#Soldadura: El spool no guarda  el WPS  con el sufijo "certificado"

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#537]
Guardo mi wps  como se encuentra marcado en amarillo 
![image](https://cloud.githubusercontent.com/assets/20443614/23270780/9d92806c-f9ba-11e6-9619-5124a8611e41.png)

Pero no se Guarda "Certificado"
![image](https://cloud.githubusercontent.com/assets/20443614/23270822/c4613288-f9ba-11e6-8ffb-83314fa7c2f1.png)

**Comment by emartinezd** [comment]
Es al momento de recuperar la informacion, no revisa si esta certificado o no, no se guarda el certificado

**Comment by emartinezd** [comment]
Lo pidio eso? por que es un algoritmo, y hacer la comparacion registro por registro, hara que se tarde mas el obtener la informacion al momento de recuperar el grid

**Comment by emartinezd** [comment]
yy no es sufijo, es prefijo xD
