### ISSUE TITLE
#Sistema de pintura: No tienen numero de control algunos SPool Id

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#559]
![image](https://cloud.githubusercontent.com/assets/20443614/23621938/4025e59e-0262-11e7-86f4-a90434c2c1ff.png)
![image](https://cloud.githubusercontent.com/assets/20443614/23621977/6dd3f9c2-0262-11e7-80a6-6e82360de720.png)

**Comment by rrojasl** [comment]
no se encuentra  en la tabla de orden de trabajo se usa para obtener el numero de control.
select * from sam2.sam.dbo.spool where Nombre='B1AE00-20VA29050-01-01-01'
select * from sam2.sam.dbo.ordentrabajospool  where SpoolID=80481
