### ISSUE TITLE
#Encintado y Etiquetado:  No se muestra los spools con cuadrante "Sin Localización " cuando se  busca solo con la zona 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#566]
Cuando Filtro por Zona y Cuadrante sin localización, se muestran varios spools en el Grid
![image](https://cloud.githubusercontent.com/assets/20443614/23666731/77cdb728-0321-11e7-99d8-326023a8f9c4.png)

Ahora selecciono solo el input de Zona y busco en el filtro del grid sin, 
pero no se encuentra ningun spool 
![image](https://cloud.githubusercontent.com/assets/20443614/23666945/f77c8f8a-0321-11e7-9b2c-b742e093d58d.png)

**Comment by iriscsd** [comment]
Deberia aparacer tambien aquellos sin localizacion, ya se resolvio issue
