### ISSUE TITLE
#Revisión SPool: o de guarda la "palomita" despues de dar clic en guardar

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#571]
Filtros en version no sirven 
![image](https://cloud.githubusercontent.com/assets/20443614/23683021/588f067e-035c-11e7-94c2-98e7444d611d.png)

**Comment by rrojasl** [comment]
No es issue porque al generar una version se muestra en la columna version y si necesitamos generar una nueva version seleccionamos la palomita.
