### ISSUE TITLE
#Revisión Pintura: De donde se esta obteniendo el sistema de pintura 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#590]
Se muestra los siguientes sistemas de pintura en el listado 
![image](https://cloud.githubusercontent.com/assets/20443614/23862038/8f5fc264-07d1-11e7-838b-054396a00cfe.png)

Pero en la pantalla de listado de pintura solo se encuentra un sistema de pintura
![image](https://cloud.githubusercontent.com/assets/20443614/23862104/c378b68c-07d1-11e7-8809-4cbe0e6a3da0.png)

**Comment by rrojasl** [comment]
Recuerda que la base de datos de che que es la que se sube a QA tienen que truncar las tablas de SP porque si no, se están tomando sistemas de pintura creados ya con anterioridad y esto da como resultado incongruencia en la información.
