### ISSUE TITLE
#Asignar Requisición: El popup cambia de tamaño cuando hay filas marcadas en rojo 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#594]
Inicio una captura, ya tengo 2 requisiciones capturadas, doy clic en guardar, por lo tanto se marca en rojo las filas  que no estan capturadas
![image](https://cloud.githubusercontent.com/assets/20443614/23871086/96a9d920-07ee-11e7-8c91-8bda1ac7ab7c.png)

Selecciono el link de Elementos, se abre el popup, selecciono una requisicion y doy clic en separar, 
![image](https://cloud.githubusercontent.com/assets/20443614/23871124/bdff025c-07ee-11e7-96d1-53e156ca3228.png)

Se abre el popup y esta enorme .. kha VRGA?''
![image](https://cloud.githubusercontent.com/assets/20443614/23871152/d4881694-07ee-11e7-8197-4085a0c7c317.png)

Quitar la "X"
![image](https://cloud.githubusercontent.com/assets/20443614/23871180/f025fb64-07ee-11e7-957f-dedb8551c4a7.png)

Si no existen filas marcadas en rojo 
![image](https://cloud.githubusercontent.com/assets/20443614/23871230/17c993f6-07ef-11e7-949b-e9f5f0ab171d.png)

El popup esta mas chico.. kha VG?
![image](https://cloud.githubusercontent.com/assets/20443614/23871038/695415da-07ee-11e7-966e-1ca9f2d659cd.png)

**Comment by emartinezd** [comment]
no me sale :( 

ya me salio xD
