### ISSUE TITLE
#Armado: Pruebas en ingles, catalogo de taller debe estar en ingles 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#604]
![image](https://cloud.githubusercontent.com/assets/20443614/23914967/3427831e-08ad-11e7-90e7-0c2b852eb93c.png)

**Comment by rrojasl** [comment]
El catalogo que se consulta es SAM2.SAM.dbo.Taller y no tiene la columna de español e ingles.
