### ISSUE TITLE
#Carga de carro: Cada que se cambie el carro, el sistema debe de mostrar un popup, Los registros capturados no han sido guardados¿Desea continuar? 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#630]
Selecciono el carro Mery001 se muestran los spools, vuelvo a cambiar el carro y el sistema me permite seleccionar otro carro, sin actualizar la información
![image](https://cloud.githubusercontent.com/assets/20443614/24617768/85c103b4-185a-11e7-812d-e85999eeb320.png)

**Comment by rrojasl** [comment]
Meri duda se cambia el carro no aparece nada pero al presionar el boton mostrar o enter si aparece esto es la funcionalidad que yair dijo en un momento solo el ultimo elemento al dar enter o al presionar el boton mostrar produciria ese evento.
