### ISSUE TITLE
#Carga de plana: Se están duplicando juntas en el combo 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#641]
![image](https://cloud.githubusercontent.com/assets/20443614/24682604/256bdc80-1960-11e7-8c9f-ac1a0407fef4.png)

**Comment by emartinezd** [comment]
Falta de integridad, al parecer el proyecto de Retificar y Ramones estan activos, y los 2 tienen la R como prefijo para las ordenes de trabajo
