### ISSUE TITLE
#Carga de Carro: Cambiar el estilo correcto del popup 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#649]
![image](https://cloud.githubusercontent.com/assets/20443614/24771843/ba99d134-1ad4-11e7-988d-7fb6daa28420.png)
![image](https://cloud.githubusercontent.com/assets/20443614/24771929/24f0c1fa-1ad5-11e7-98ac-fc9d7a3501ea.png)

El popup debe de tener en el encabezado del popup "Advertencia "
![image](https://cloud.githubusercontent.com/assets/20443614/24771873/e83480b2-1ad4-11e7-9788-38c156a8b770.png)

**Comment by MeriverQuerido** [comment]
En vez de agregar el titulo de encabezado, quitaste el popup

**Comment by rrojasl** [comment]
duda con Yair.
