### ISSUE TITLE
#ARmado : Cuando un spool se encuentra en la pantalla de Revisión embarque, se debe dejar de mostrar en las patallas

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#655]
El spool X001-012 ya se encuentra en la pantalla de Revisión embarque
![image](https://cloud.githubusercontent.com/assets/20443614/24778959/0cce2fae-1af3-11e7-8995-8f57592df0f4.png)

Sin embargo al agregarlo en las pantallas de Armado y soldadura, si se agrega el spool
![image](https://cloud.githubusercontent.com/assets/20443614/24778999/35c8dd5a-1af3-11e7-82cb-f3e2d88e1075.png)

En encintado ya no se muestra el spool asi que esta bien 
![image](https://cloud.githubusercontent.com/assets/20443614/24779110/c8e10c0c-1af3-11e7-9d21-eba8d16ed2bc.png)

**Comment by rrojasl** [comment]
El motivo es porque se ocupa la tabla  Sam3_SpoolWorkStatus el campo SpoolCertificado y el proceso de embarque ya no lo esta actualizando. por esa razón aparece en los demás modulos.
