### ISSUE TITLE
#Carga de carro: El sistema no me deja agregar un spool. 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#666]
Quiero agregar el spool X001-001 al carro sin embaargo el sistema muestra un popup de tipo advertencia, que no tiene un SP.
![image](https://cloud.githubusercontent.com/assets/20443614/24870884/702c0606-1ddd-11e7-83b7-357136b06899.png)

Al consultarlo en la pantalla de Sistema de pintura aplicable, el sistema muestra un popup de que el spool X001-001 ya se encuentra en un carro.
![image](https://cloud.githubusercontent.com/assets/20443614/24870976/be07e854-1ddd-11e7-88fd-dbaa2318626c.png)

**Comment by rrojasl** [comment]
Meri el problema es que ya se hicieron pruebas con esos spools y la bd SAM de QA tiene el campo cuadranteID como null. por esa razón no al hacer los cruces de los spools que tiene el proyecto-usuario se ocupa el catalogo de cuadrante y como no hace match no aparece. y en la pantalla de sistema de pintura aplicable no se hace ese cruce por esa razón si aparece.

**Comment by rrojasl** [comment]
Agregue un mensaje donde indico que el el spool no tiene un sp o que el cuadrante no es valido ya que hago un inner join, estaría a consideración del cliente que si en algún momento el spool no tiene un cuadrante valido se haga un left join.
