### ISSUE TITLE
#Carga de carro: No se muestra los spools en el escenario de Escritorio  

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#668]
Selecciono el carro PX002 que tiene 2 spools cargados, sin embargo en el escenario de escritorio no me muestra nada 
![image](https://cloud.githubusercontent.com/assets/20443614/24871462/4824ef5e-1ddf-11e7-9786-165a8520aed1.png)

**Comment by rrojasl** [comment]
Meri ya te había comentado que esto es porque escritorio depende que en la tabla spoolworkstatus en la columna "ok pnd" se tenga habilitado.

**Comment by rrojasl** [comment]
Meri ya te había comentado que esto es porque escritorio depende que en la tabla spoolworkstatus en la columna "ok pnd" se tenga habilitado.

**Comment by rrojasl** [comment]
Meri esto es una duda para Yair porque el escenario es el siguiente si cargo un spool con la opción de patio y después por medio de la pantalla de okpnd habilitan ese spool entonces si revisan el escenario de escritorio aparecerán dos elementos y me indicaran que es un issue, que se repiten los spools entonces que se hace en esos casos cual quito? o si existirá una validación adicional en el proceso de pnd´s
