### ISSUE TITLE
#Revisión Embarque: No se muestran todos los proyectos en el listado

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#675]
![image](https://cloud.githubusercontent.com/assets/20443614/24885827/4c42a1c6-1e16-11e7-8459-d6983cb14883.png)

**Comment by emartinezd** [comment]
Solo se mostraran los proyectos, que necesiten revision del cliente, la cual se puede ver en la tabla Sam3_ProyectoConfiguracion
