### ISSUE TITLE
#Sistema de pintura: Incongruencia en las filas marcadas de rojo 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#676]
El proceso de primario y shotblast tienen capturada la misma información en las columnas, sin embargo un proceso se marca de rojo y el otro no 

![image](https://cloud.githubusercontent.com/assets/20443614/24913293/4a9ef4c0-1e96-11e7-8480-097d9626b6e5.png)

**Comment by rrojasl** [comment]
realice el flujo y no aparece podrias indicarme el flujo porfavor
