### ISSUE TITLE
#Sistema de pintura: El sistema no manda mensaje cuando se le quita la "✓" de la columna del proceso

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#677]
Esta es una captura después de haber guardado un SP
![image](https://cloud.githubusercontent.com/assets/20443614/24913491/f9f03808-1e96-11e7-8529-5ade337b5825.png)

Esta es una captura nueva 
![image](https://cloud.githubusercontent.com/assets/20443614/24913555/21088ac6-1e97-11e7-9905-20b2c882ebdb.png)

**Comment by rrojasl** [comment]
Hice el flujo y no aparece nada.. podrías ayudarme indicándome que flujo realizaste porfavor
