### ISSUE TITLE
#68 Empaquetado: Edita no se bloquean los controles 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#68]
Puedo seleccionar del listado de paquete
![image](https://cloud.githubusercontent.com/assets/20443614/20673683/b158126e-b54b-11e6-842a-f555d31b4079.png)
y listado de spools
![image](https://cloud.githubusercontent.com/assets/20443614/20673702/c229aa94-b54b-11e6-9557-b2c75dea2287.png)

**Comment by iriscsd** [comment]
Issue corregido, pendiente por validar
