### ISSUE TITLE
#Carga de Carro: No puedo descargar

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#682]
Quiero descargar un spool y el sistema no me deja 
![image](https://cloud.githubusercontent.com/assets/20443614/24920349/80f5a33c-1eac-11e7-9eee-272df4a51bd8.png)

**Comment by rrojasl** [comment]
Es porque tiene que estar poblada la tabla Sam3_SpoolUbicacion, y por esa razón se tiene que implementar el trigger de sam2 a sam3

**Comment by MeriverQuerido** [comment]
@rrojasl  la primera descarga funciona ya después no se puede descargar el spool 
![image](https://cloud.githubusercontent.com/assets/20443614/24980834/92ba5c72-1f9f-11e7-9d9e-dc996b241b67.png)

al igual en el escenario de escritorio 
![image](https://cloud.githubusercontent.com/assets/20443614/24981988/ce828ca2-1fa4-11e7-9371-21fc07a13751.png)

**Comment by MeriverQuerido** [comment]
@rrojasl  sigo sin poder descargar
![image](https://cloud.githubusercontent.com/assets/20443614/25254596/f75ba9b8-25eb-11e7-8f9f-8f14008f9e95.png)

**Comment by MeriverQuerido** [comment]
@rrojasl  sigo sin poder descargar
![image](https://cloud.githubusercontent.com/assets/20443614/25393934/799080fc-29a2-11e7-9a81-88b7680d9664.png)
