### ISSUE TITLE
#Carga de carro: No puedo agregar el spool X001-011 al carro 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#684]
Quiero agregar el spool X001-011 pero el sistema muestra un mensaje que el spool no tiene un sistema de pintura seleccionado o un cuadrante invalido 
![image](https://cloud.githubusercontent.com/assets/20443614/24923157/46bcbc00-1eb6-11e7-899a-f18dabb66b76.png)

sin embargo al revisar el sp en la pantalla de SP Aplicable, el spool si tiene sp asignado
![image](https://cloud.githubusercontent.com/assets/20443614/24923270/9e29264a-1eb6-11e7-8ca0-c2f76caa72cb.png)

**Comment by rrojasl** [comment]
El motivo es porque por cuestiones de pruebas en QA el spool tiene el cuadrante null por esa razón no lo puedes agregar, en el mensaje comente que puede ser porque no tiene un sistema de pintura o porque el cuadrante no es valido.
