### ISSUE TITLE
#Carga de carro: No es correcto el popup con la acción realizada

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#694]
Quiero agregar un spool, pero el sistema muestra un mensaje que el spool no tienen sp o que no tiene cuadrante
![image](https://cloud.githubusercontent.com/assets/20443614/24979312/4c85c40e-1f99-11e7-8042-60439918ce77.png)
sin embargo rectifico en la pantalla de SP Aplicable, y el spool si tiene SP
![image](https://cloud.githubusercontent.com/assets/20443614/24979394/93011b9a-1f99-11e7-98ca-ac686bed1dce.png)

El mensaje correcto, "El spool seleccionado tiene diferente Sistema de pintura"

**Comment by rrojasl** [comment]
si un spool no tiene un cuadrante valido por esa razón mando el mensaje adjunto a "SP no valido o Cuadrante no valido",  ¿Todos los spools tienen un cuadrante valido? si es así quito el mensaje que me indicas
