### ISSUE TITLE
#Carga de carro: De selecciono un spool que ya se encontraba cargado en un carro y al guardar sigue seleccionado

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#696]
De selecciono el spool X001-009 y al guardar sigue marcado el spool 
![image](https://cloud.githubusercontent.com/assets/20443614/24981906/6606e1aa-1fa4-11e7-91cc-66e23adfa169.png)
![image](https://cloud.githubusercontent.com/assets/20443614/24981946/8f2a8f78-1fa4-11e7-9db4-1aaa686d40bc.png)

**Comment by rrojasl** [comment]
Para que ya no se encuentre seleccionado se tiene que descargar el spool o cuando ya se encuentre cargado el spool desaparesco el checkbox?
