### ISSUE TITLE
#Carga de carro: El sistema se queda pensando cuando consulto otros carros

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#715]
![image](https://cloud.githubusercontent.com/assets/20443614/25394519/d7291002-29a3-11e7-97ed-0e52f6c74bc6.png)

**Comment by rrojasl** [comment]
máximo se tarda 60 segundos, puede ser porque estoy con wifi y el internet de la oficina esta lento.
