### ISSUE TITLE
#Carga de carro: por default se debe de mostrar la zona y el cuadrante

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#720]
![image](https://cloud.githubusercontent.com/assets/20443614/25397675/b49cd1d0-29ae-11e7-95ea-c0dcd97f5064.png)

Selecciono la zona y el cuadrante, y al descargar me manda error
![image](https://cloud.githubusercontent.com/assets/20443614/25397785/2f4caa40-29af-11e7-8137-16a1bdd3fed4.png)

**Comment by rrojasl** [comment]
Favor de limpiar la bd correctamente 

update Sam2.sam.dbo.spool set CuadranteID=null

truncate table  sam.dbo.cuadrantehistorico 

delete from   Sam3_cuadrante where PatioID=7 -- son solo los cuadrantes de tipo carro etc
truncate table  Sam3_spoolubicacion
truncate table sam3_cuadrantehistorico

truncate table Sam3_Pintura_carro
truncate table [dbo].[Sam3_Pintura_CargaCarro]
truncate table [dbo].[Sam3_Pintura_CargaCarrodetalle]
