### ISSUE TITLE
#Carga de carro: No se muestra el spool después de descargarlo 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#721]
Se encuentran 2 spools en carro "2Prueba" con sp 20.01SEC
Estoy filtrando por sistema de pintura 
![image](https://cloud.githubusercontent.com/assets/20443614/25398608/49c5fea0-29b2-11e7-97bd-c8a3aabb0d90.png)

y al descargarlo, ya no se muestra el spool 
![image](https://cloud.githubusercontent.com/assets/20443614/25398660/6eb4d998-29b2-11e7-84b1-33c71f2a9b0c.png)

**Comment by rrojasl** [comment]
El problema es por el internet ya optimice el query con 17000 registros se tarda 10 seg cuando lo del internet funcione bien se tiene que validar
