### ISSUE TITLE
#Carga de carro: El sistema tarda para mostrar inf en el grid en el escenario de escritorio 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#723]
![image](https://cloud.githubusercontent.com/assets/20443614/25442079/a7ff38ee-2a69-11e7-883f-a216c05ae4dc.png)

**Comment by rrojasl** [comment]
No se si se deba a cuestiones de la red de la oficina , lo estoy probando en mi casa y tarda 30 seg aprox.
