### ISSUE TITLE
#carga de carro: Algunos spools se muestra el patio y cuadrante

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#725]
![image](https://cloud.githubusercontent.com/assets/20443614/25443412/60f99076-2a6d-11e7-9e1f-f75f99798133.png)

**Comment by rrojasl** [comment]
El motivo es los cuadrantes que nunca han sido utilizados no tienen un cuadrante historico por lo tanto aparece la zona y el cuadrante vacio.

![pantalla sin historico spool](https://cloud.githubusercontent.com/assets/14182754/25448853/7f186bec-2a7f-11e7-91eb-1ecc2ccf7027.PNG)
