### ISSUE TITLE
#Carga de Carro: Ajustar texto no sirve (Clic derecho ajustar texto)

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#731]
![image](https://cloud.githubusercontent.com/assets/20443614/25445362/cf9995de-2a73-11e7-92b1-862eb36e273b.png)

**Comment by rrojasl** [comment]
sirve pero al no tener informacion "amontonada" pareceria que no hace nada. si configuro para que una columna sea mas pequeña y se "amontona" pero al usar esa opcion hace su funcionalidad.
