### ISSUE TITLE
#Descarga de carro: Ajustar texto no sirve 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#732]
![image](https://cloud.githubusercontent.com/assets/20443614/25445389/e2927b6a-2a73-11e7-8645-1e640040d78f.png)

**Comment by rrojasl** [comment]
Mismo caso que carga de carro el ajustar texto no es para que una columna se haga mas pequeña o mas grande si no que dependiendo de la informacion del grid si no cabe en la celda se hace mas grande la celda en lo "alto".
