### ISSUE TITLE
#OK PND: no se muestra nada en el grid 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#745]
Selecciono el proyecto y el spool pero no se muestra nada ¿?
![image](https://cloud.githubusercontent.com/assets/20443614/25487752/c6acae90-2b2a-11e7-96fa-c814be7ba914.png)

**Comment by jgutierrez01** [comment]
Cuando se busca por el numero de control, y los datos son mínimos por ejemplo (X0, 00, 0, X) esto generará una búsqueda que contenga al menos esos datos y por ende la búsqueda tardará mas en ejecutarse.
