### ISSUE TITLE
#sISTEMA DE PINTURA: CAMBIAR EL ORDEN DE EJECUCIÓN AL INICIO DE LA PANTALLA

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#747]
Al inicio se muestra la pantalla como en la siguiente imagen 
![image](https://cloud.githubusercontent.com/assets/20443614/25489143/939546a8-2b2e-11e7-97ac-76a5d9b1af2c.png)

ya despues se carga

**Comment by rrojasl** [comment]
Es por el internet una prueba de eso es por que el menu lado izquierdo no esta cargado al 100%
