### ISSUE TITLE
#Sistema de pintura: Ajustar texto no sirve 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#748]
![image](https://cloud.githubusercontent.com/assets/20443614/25490740/54a42cd4-2b33-11e7-95fa-9c85985fc231.png)

**Comment by rrojasl** [comment]
Mismo caso que en anteriores pantallas el ajustar texto no es para modificar " online " el ancho de una columna si no para modificar el "alto" es decir si una columna tiene tiene un espacio de |******..| el ajustar texto hace 
|*****|
|**    |
