### ISSUE TITLE
#Carga de plana, empaquetado: Se puedo agregar el mismo spool en ambas pantallas

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#772]
Agrego el spool P020 002 a la plana y lo guardo 
![image](https://cloud.githubusercontent.com/assets/20443614/25668215/ac07ceba-2feb-11e7-8962-f1da924f4301.png)

y agrego el mismo spool a  un paquete y el sistema me permite guardarlo 
![image](https://cloud.githubusercontent.com/assets/20443614/25669500/536bb222-2fef-11e7-878c-75c680edabd9.png)

**Comment by emartinezd** [comment]
Mas bien es... se agrega en las 2 pantallas en paralelo, y al momento de guardar, una antes que la otra, pero ya agregado el elemento, no se valida en tiempo real, que ya esta asignado el spool en  otro paquete o plana
