### ISSUE TITLE
#Etiquetado, Encintado : El  mensaje de toma de decisión dice que la consulta triara mas de 100 registros, y en el grid no trae esos registros 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#778]
![image](https://cloud.githubusercontent.com/assets/20443614/25673601/98d38b92-2ffd-11e7-883e-2c87eb68a457.png)

Solo se muestran 2 spools en el grid 
![image](https://cloud.githubusercontent.com/assets/20443614/25673627/ab8fd844-2ffd-11e7-9da6-444b9068f457.png)

**Comment by emartinezd** [comment]
Problema al traer al parecer mas de 10,000 registros, no hay suficiente memoria, y truena, y pareciera, que no trae nada
