### ISSUE TITLE
#Descarga de carro: Carros repetidos en el catalogo

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#798]
![image](https://cloud.githubusercontent.com/assets/20443614/25860804/526a4e20-34a8-11e7-8bca-afd42b0c8a62.png)

**Comment by rrojasl** [comment]
Cuando se limpie la bD favor de borrar los cuadrantes del patio 7 en la tabla de cuadrantes de sam2.
