### ISSUE TITLE
#Listado de Embarque: Se desaparecen los btn de enviar al dar clic en guardar

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#806]
A todos los embarques que se encuentran en el grid ya se les dio el ok para ser enviados, doy clic en guardar 
![image](https://cloud.githubusercontent.com/assets/20443614/26071709/9b3d9a56-396e-11e7-870b-f051a9852384.png)

despues de que se guarda la informacion los proyectos de etileno y ramones solo conservaron el btn de enviar
![image](https://cloud.githubusercontent.com/assets/20443614/26071760/c5d14204-396e-11e7-91f4-e0f546c6d70b.png)

**Comment by emartinezd** [comment]
Segun yo, esta parte ya no me corresponde a mi
