### ISSUE TITLE
#Se sigue mostrado los spools de un embarque que ya fue enviado y cerrado.

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#820]
Cierro el embarque ' R004-EMB' y doy clic en guardar 
![image](https://cloud.githubusercontent.com/assets/20443614/26121436/d3b9fed0-3a39-11e7-9b5d-95ab2964c054.png)

POR LO TANTO LOS SPOOL QUE ESTABAN EN DICHO EMBARQUE NO SE DEBEN DE MOSTRAR 
*EN ARMADO SE SIGUE MOSTRANDO 
![image](https://cloud.githubusercontent.com/assets/20443614/26121984/980fde5c-3a3b-11e7-89c2-2e81c03821bb.png)

* SOLDADURA 
![image](https://cloud.githubusercontent.com/assets/20443614/26122008/a96b3854-3a3b-11e7-8be2-2488604ae74d.png)

* OK PND 
![image](https://cloud.githubusercontent.com/assets/20443614/26122027/ba0ed968-3a3b-11e7-93f3-cde0392ebb06.png)

* CARGA DE PLANA
Los spools que ya fueron embarcados no se deben de agrega, sin embargo la app me lo permite y dice que el spool se encuentra en la una plana- proovedor, pero no es cierto -
Ser más especifico en el mensaje
![image](https://cloud.githubusercontent.com/assets/20443614/26122193/42d8e59a-3a3c-11e7-97a7-f50d607e189d.png)

**Comment by rrojasl** [comment]
Seguro es porque no han actualizado en algún proceso la tabla Sam3_Spoolworkstatus en el campo Spoolcertificado

**Comment by rrojasl** [comment]
favor de revisarlo @jgutierrez01 @emartinezd

**Comment by emartinezd** [comment]
Es la pregunta a Yair, si se pueden visualizar como read only, o no

**Comment by jgutierrez01** [comment]
En el proceso de revisión de embarque los spools que llegaron se certifican y los que no (manuales y que no llegaron) seguirán mostrándose, pero están en cuadrante sin localización
