### ISSUE TITLE
#Carga de carro: El sistema no me permite descargar 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#821]
Quiero descaragar el spool S001-020 y el sistema manda un mensaje de error
![image](https://cloud.githubusercontent.com/assets/20443614/26214242/47917116-3bc1-11e7-928e-22caaa7eada4.png)

**Comment by rrojasl** [comment]
Meri limpiaste la bd correctamente? esa es una de las razones por la cual no se puede descargar los spools por incongruencia de informacion

**Comment by rrojasl** [comment]
Te confirmo al borrar las tablas de cuadrante tambien se tiene que borrar las tablas de carga de carro porque el carro es un cuadrante entonces al no borrar los carros "se queda" y despues hay incongruencia de informacion, favor de borrar las tablas de carga de carro.
