### ISSUE TITLE
#Carga de plana: un warning especial cuando la plana ya este en el proceso de embarque 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#822]
Quiero agregar el spool P001-001 a la plana  , sin embargo el sistema no me lo permite pero me da el proveedor y la plana en el que se encuetra el spool 
![image](https://cloud.githubusercontent.com/assets/20443614/26251932/812647d6-3c74-11e7-9a9c-4f7020456cb4.png)

verifico, pero en el catalogo de planas no se encuentra
![image](https://cloud.githubusercontent.com/assets/20443614/26252062/d180175c-3c74-11e7-831f-00d1b64f1183.png)

El spool ya se encuentra en el proceso de preparación embarque 
![image](https://cloud.githubusercontent.com/assets/20443614/26252098/f415d93c-3c74-11e7-8170-75060838e111.png)

**Comment by emartinezd** [comment]
Es que fisicamente esta en una plana, asi lo pidio yair, en la siguiente junta lo comentto
