### ISSUE TITLE
#Avance: Porque no esta el grid cuando se inicia la pantalla 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#832]
![image](https://cloud.githubusercontent.com/assets/20443614/26504297/a636a7ec-4209-11e7-9281-be78210d81fe.png)

**Comment by rrojasl** [comment]
No aparece porque el grid es "Dinamico" depende de un carro que tiene un sistema de pintura y ese sistema de pintura tiene componentes y reductores , al no seleccionar carro no tiene caso mostrar el grid.
