### ISSUE TITLE
#Avance: No me gusta el maquetado

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#833]
El planchado esta muy a la derecha,
no están alineados los componentes 
![image](https://cloud.githubusercontent.com/assets/20443614/26504647/0acf6490-420b-11e7-9c54-2a59a6bec695.png)

**Comment by rrojasl** [comment]
Podríamos revisar este punto con yair porque el maquetado también es dinámico y no esta alineado por que el control de "trabajador" es un "multiselect" y ocupa mas espacio.
