### ISSUE TITLE
#Avance: No se bloquea el btn de versión 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#839]
![image](https://cloud.githubusercontent.com/assets/20443614/26608174/d3ee2f4e-455f-11e7-8f4c-eb05ae280650.png)

**Comment by rrojasl** [comment]
Por el momento lo deje sin funcionalidad solo esta maquetado el motivo Yair pidio una funcionalidad extra pero tengo dudas de como tiene que interactuar con la pantalla.
