### ISSUE TITLE
#Dynasol: Se guardan campos vacíos 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#848]
Elimino  campos del grid 
![image](https://cloud.githubusercontent.com/assets/20443614/26648457/26b5b69a-4608-11e7-9eca-f7cb73aa3b6c.png)

Pero al dar clic en guardar el sistema no me marca error por las filas, 
Después del guardado  se regresa la información que ya se encontraba en las celdas
![image](https://cloud.githubusercontent.com/assets/20443614/26648488/3fd2d162-4608-11e7-872d-5897a6497845.png)

¿No se deberían de marcar en rojo las filas ?

**Comment by emartinezd** [comment]
Eso no es error

**Comment by emartinezd** [comment]
Es error, por que no deberia ser editable,
