### ISSUE TITLE
#SP aplicable: *Solo en esta pantalla y algunas de pintura* Se sigue mostrando los spools a pesar de que ya se envio el embarque 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#923]
![image](https://user-images.githubusercontent.com/20443614/27199706-97e3d358-51dc-11e7-8f62-780965841831.png)

**Comment by jgutierrez01** [comment]
En este proceso yo certifico los spools en la tabla SpoolWorkStatus, @rrojasl puedes revisar si ocupas alguna otra bandera en esa tabla, gracias.
