### ISSUE TITLE
#Etiquetado:  Cuando consulto por 3 dígitos sale en sig mensaje en rojo 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#927]
![image](https://user-images.githubusercontent.com/20443614/27365621-9d75d4a0-5606-11e7-8776-cc76c9b95e6b.png)
![image](https://user-images.githubusercontent.com/20443614/27365753-619df0e2-5607-11e7-9619-f78e496e71a9.png)

**Comment by emartinezd** [comment]
Son demasiados cuadrantes, y se muere la consulta, no se si habra que hacer otro filtro mas 
para que forzosamente le pongas una letra, para que sepa que proyecto es, y luego ya con eso hacer mas reducido el numero de opciones, por que la opcion, fue hecha asi, por si solo anotaban numeros, pero es demasiada informacion
