### ISSUE TITLE
#Encintado y Etiquetado: No se muestra spools cuando consulto por SPOOL ID 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#928]
![image](https://user-images.githubusercontent.com/20443614/27365846-f86c88a8-5607-11e7-9d10-94e38a47ee40.png)
![image](https://user-images.githubusercontent.com/20443614/27365850-fe142d1a-5607-11e7-86a3-f03037da4b8c.png)

**Comment by emartinezd** [comment]
Por lo del cuadrante que seteaban a null, no trae nada
