### ISSUE TITLE
#Listado Embarques Cerrado, Listado Embarque Enviados: Explícame como poderlas consultar

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#935]
El combo, de periodo no se muestra nada aunque ya seleccione un proyecto.
![image](https://user-images.githubusercontent.com/20443614/27465890-0e854dc4-579c-11e7-93fa-34ab8203a6b8.png)

Verifica, si los listados llevan los btn, ambos listados deben llevar lo mismo 
![image](https://user-images.githubusercontent.com/20443614/27465926-5424e632-579c-11e7-95b1-3d4d69954542.png)

![image](https://user-images.githubusercontent.com/20443614/27465934-662abb18-579c-11e7-981b-152aaaa8c844.png)

**Comment by jgutierrez01** [comment]
En listado de **Embarques Enviados** no se como es la parte de los periodos, no hice esa pantalla, La que hice fue la de **embarques Cerrados** en esa pantalla solamente se podrá consultar aquellos embarques que ya fueron cerrados y que están con cliente, puedes elegir aquellos embarques por proyectos o por un rango de fechas especificas.

**Comment by jgutierrez01** [comment]
@emartinezd La pantalla de Listado de Embarques Enviados aun sigue funcional ese maquetado? o lo adapto a como esta el listado de Embarques Cerrados?.
