### ISSUE TITLE
#ARMADO: Esta bloqueado el combo de spool id, y se tiene C

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#936]
Esta bloqueado el spool id 
![image](https://user-images.githubusercontent.com/20443614/27466064-65366dbe-579d-11e7-952e-beb8a3167f50.png)

y se desbloquea hasta que pongo C001
![image](https://user-images.githubusercontent.com/20443614/27466070-7c679a3a-579d-11e7-9f46-686279dd606e.png)

Puede que se deba a que cerre el embarque Croossover
![image](https://user-images.githubusercontent.com/20443614/27466098-b60feb48-579d-11e7-8432-5479e87ea9ad.png)

Cuando empiezo a interactuar
 

![image](https://user-images.githubusercontent.com/20443614/27468456-8f2ad652-57af-11e7-9602-b6b212d06b45.png)

**Comment by rrojasl** [comment]
Puede ser por le cache del navegador ya lo revise desde mi celular desde otra pc y no aparece el error.
