### ISSUE TITLE
#Armado: No se estan guardando los números únicos 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#942]
Capturo guardo y los números únicos asignados desaparecen 
![image](https://user-images.githubusercontent.com/20443614/27468558-0fb86e38-57b0-11e7-8963-543432c09e90.png)
![image](https://user-images.githubusercontent.com/20443614/27468567-1dcdae8e-57b0-11e7-8a8b-5c3ae682b01e.png)

**Comment by rrojasl** [comment]
Fue por peticion de yair que para el proyecto de etileno no se guardaran lo NU.
