### ISSUE TITLE
#Inspeccion visual dimensional:  EL spool X001-009 por que no tiene juntas 

### ISSUE THREAD

**Issue by MeriverQuerido** [rrojasl/Steelgo-QA#943]
![image](https://user-images.githubusercontent.com/20443614/27468664-c6ef111a-57b0-11e7-9cfc-a8673f634da3.png)

**Comment by emartinezd** [comment]
Todas las juntas de ese Spool estan en FIELD y no en SHOP, por lo que no se le puede capturar nada
